- name: Download Node Exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz
    dest: /tmp/node.tar.gz

- name: Extract
  unarchive:
    src: /tmp/node.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Start Node Exporter
  shell: nohup node_exporter &
